export enum MovementType {
    PURCHASE = 'PURCHASE',
    SALE = 'SALE',
    TRANSFER_IN = 'TRANSFER_IN',
    TRANSFER_OUT = 'TRANSFER_OUT',
    ADJUSTMENT_IN = 'ADJUSTMENT_IN',
    ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',
    RETURN_IN = 'RETURN_IN',
    RETURN_OUT = 'RETURN_OUT',
    RESERVATION = 'RESERVATION',
    RELEASE_RESERVATION = 'RELEASE_RESERVATION',
    INITIAL_STOCK = 'INITIAL_STOCK',
}